# Generated by Django 3.2.6 on 2022-03-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
