# Generated by Django 3.2.6 on 2022-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
