# Generated by Django 3.2.6 on 2022-03-09 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0003_productdb_category'),
        ('shopapp', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailymartapp.productdb')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.registerdb')),
            ],
        ),
    ]
