# Generated by Django 3.2.6 on 2022-03-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0003_productdb_category'),
        ('shopapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='cartdb',
        ),
    ]
